<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

    <modelVersion>4.0.0</modelVersion>

    <groupId>gt.edu.umg</groupId>
    <artifactId>comparacion-soap-rest</artifactId>
    <version>1.0.0</version>
    <packaging>pom</packaging>

    <name>comparacion-soap-rest</name>
    <description>Misma operacion expuesta como servicio SOAP y como servicio REST</description>

    <modules>
        <module>soap</module>
        <module>rest</module>
    </modules>

    <properties>
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <jaxws.version>4.0.2</jaxws.version>
        <spring.boot.version>3.3.4</spring.boot.version>
    </properties>

</project>
